// ----------------------------------------------------------
// NYC Bus Infrastructure Map
// Static data generated by GitHub Actions
// ----------------------------------------------------------

// ----------------------------------------------------------
// Map Initialization
// ----------------------------------------------------------

const map = L.map("map", {
  preferCanvas: true
}).setView([40.71, -74.00], 12);

L.tileLayer(
  "https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png",
  {
    attribution: "© OpenStreetMap contributors © CARTO",
    maxZoom: 19
  }
).addTo(map);

proj4.defs(
  "EPSG:2260",
  "+proj=lcc +lat_1=40.66666666666666 +lat_2=41.03333333333333 " +
  "+lat_0=40.16666666666666 +lon_0=-74 +x_0=984250 +y_0=0 " +
  "+datum=NAD83 +units=us-ft +no_defs"
);

// ----------------------------------------------------------
// Layers
// ----------------------------------------------------------

const busStopsLayer = L.layerGroup();
const busRoutesLayer = L.layerGroup();
const busSignsLayer = L.layerGroup();
const busLanesLayer = L.layerGroup();



// List GTFS feed folders manually (add more as needed)
const GTFS_FEEDS = [
  "gtfs_bx",
  "gtfs_q",
  "gtfs_m",
  "gtfs_si",
  "gtfs_b",
  "gtfs_busco"
];


const routeColorCache = {};

function randomRouteColor(routeId) {
  // If already assigned, return it
  if (routeColorCache[routeId]) return routeColorCache[routeId];

  // Generate a random but visually pleasant color
  const hue = Math.floor(Math.random() * 360);
  const color = `hsl(${hue}, 70%, 45%)`;

  routeColorCache[routeId] = color;
  return color;
}

busStopsLayer.addTo(map);
busRoutesLayer.addTo(map);
busSignsLayer.addTo(map);
busLanesLayer.addTo(map);

L.control.layers(
  null,
  {
    "Bus Stops": busStopsLayer,
    "Bus Routes": busRoutesLayer,
    "Bus Signs": busSignsLayer,
    "Bus Lanes": busLanesLayer
  },
  {
    collapsed: false
  }
).addTo(map);

// ----------------------------------------------------------
// Utilities
// ----------------------------------------------------------


async function fetchJSON(url) {
  const resp = await fetch(url, {
    cache: "no-store"
  });

  if (!resp.ok) {
    throw new Error(`${url}: ${resp.status}`);
  }

  return resp.json();
}

async function loadRoutesForFeed(feed) {
  const text = await fetchText(`feeds/${feed}/routes.txt`);
  const rows = parseCSV(text);

  const map = {};
  rows.forEach(r => {
    map[r.route_id] = {
      short: r.route_short_name || r.route_long_name || r.route_id,
      color: r.route_color ? `#${r.route_color}` : null,
      textColor: r.route_text_color ? `#${r.route_text_color}` : "#000000"
    };
  });

  return map;
}

function safeNumber(value) {
  const n = Number(value);
  return Number.isFinite(n) ? n : null;
}

function fitToInfrastructure() {
  const groups = [
    busRoutesLayer,
    busStopsLayer,
    busLanesLayer
  ];

  let bounds = null;

  groups.forEach(layer => {
    if (
      layer.getLayers &&
      layer.getLayers().length > 0 &&
      layer.getBounds
    ) {
      const b = layer.getBounds();

      if (b.isValid()) {
        bounds = bounds ? bounds.extend(b) : b;
      }
    }
  });

  if (bounds?.isValid()) {
    map.fitBounds(bounds, {
      padding: [20, 20]
    });
  }
}

// ----------------------------------------------------------
// Coordinate Conversion
// ----------------------------------------------------------


function epsg2260ToWGS84(x_ft, y_ft) {
  // proj4 returns [lon, lat]
  const [lon, lat] = proj4("EPSG:2260", "WGS84", [x_ft, y_ft]);
  return [lat, lon];
}

// ----------------------------------------------------------
// Cached GTFS Data
// ----------------------------------------------------------
async function fetchText(url) {
  const resp = await fetch(url, { cache: "no-store" });
  if (!resp.ok) throw new Error(`${url}: ${resp.status}`);
  return resp.text();
}

function parseCSV(text) {
  const lines = text.split(/\r?\n/).filter(l => l.trim() !== "");
  const headers = lines[0].split(",");
  return lines.slice(1).map(line => {
    const cols = line.split(",");
    const obj = {};
    headers.forEach((h, i) => {
      obj[h] = cols[i];
    });
    return obj;
  });
}

async function loadGTFSFeeds() {
  for (const feed of GTFS_FEEDS) {
    try {
      console.log(`Loading GTFS feed: ${feed}`);

      const [shapesTxt, stopsTxt, routesMap] = await Promise.all([
        fetchText(`feeds/${feed}/shapes.txt`),
        fetchText(`feeds/${feed}/stops.txt`),
        loadRoutesForFeed(feed)
      ]);

      const shapes = parseCSV(shapesTxt);
      const stops = parseCSV(stopsTxt);

      drawStops(stops);
      drawShapesFromGTFS(shapes, routesMap);

      console.log(`Loaded ${feed}`);
    } catch (err) {
      console.warn(`GTFS feed ${feed} failed:`, err);
    }
  }
}

function drawShapesFromGTFS(shapes, routesMap, shapeRouteMap) {
  const grouped = {};

  shapes.forEach(row => {
    const shapeId = row.shape_id;
    if (!grouped[shapeId]) grouped[shapeId] = [];
    grouped[shapeId].push({
      lat: Number(row.shape_pt_lat),
      lon: Number(row.shape_pt_lon),
      seq: Number(row.shape_pt_sequence)
    });
  });

  Object.keys(grouped).forEach(shapeId => {
    const pts = grouped[shapeId]
      .sort((a, b) => a.seq - b.seq)
      .map(p => [p.lat, p.lon]);

    if (pts.length < 2) return;

    // route_id from shapeRouteMap (from trips.txt)
    const route_id = shapeRouteMap[shapeId] || shapeId;

    // route short name from routes.txt (optional)
    const shortName = routesMap[route_id]?.short || route_id;

    // 🎨 Random color per route
    const color = randomRouteColor(route_id);

    L.polyline(pts, {
      color,
      weight: 3,
      opacity: 0.85
    })
      .bindTooltip(shortName, {
        sticky: true,
        direction: "auto"
      })
      .addTo(busRoutesLayer);
  });
}

async function loadCachedGTFS() {
  try {
    const [stops, shapes] = await Promise.all([
      fetchJSON("data/stops.json"),
      fetchJSON("data/shapes.json")
    ]);

    drawStops(stops);
    drawShapes(shapes);

    console.log(
      `Loaded ${stops.length} stops and ${shapes.length} shapes`
    );
  } catch (err) {
    console.error("GTFS cache load failed:", err);
  }
}

// ----------------------------------------------------------
// Stops
// ----------------------------------------------------------

function drawStops(stops) {
  stops.forEach(stop => {
    const lat = safeNumber(stop.lat);
    const lon = safeNumber(stop.lon);

    if (lat === null || lon === null) return;

    // Use a light blue for bus stop markers
    L.circleMarker([lat, lon], {
      radius: 3,
      color: "#66CCFF",
      fillColor: "#66CCFF",
      fillOpacity: 0.7,
      weight: 1
    })
      .bindTooltip(stop.stop_name || stop.stop_id || "")
      .addTo(busStopsLayer);
  });
}

// ----------------------------------------------------------
// Route Shapes
// ----------------------------------------------------------

function drawShapes(shapes) {
  shapes.forEach(shape => {
    if (!Array.isArray(shape.points)) return;

    const pts = shape.points
      .map(p => {
        if (Array.isArray(p)) {
          return [Number(p[0]), Number(p[1])];
        }

        return [
          Number(p.lat),
          Number(p.lon)
        ];
      })
      .filter(
        p =>
          Number.isFinite(p[0]) &&
          Number.isFinite(p[1])
      );

    if (pts.length < 2) return;

    L.polyline(pts, {
      color: "#6f42c1",
      weight: 2,
      opacity: 0.6
    })
      .bindTooltip(shape.route_id || "")
      .addTo(busRoutesLayer);
  });
}

function routeColor(routeShortName) {
  // deterministic color seed
  const hash = [...routeShortName].reduce((a, c) => a + c.charCodeAt(0), 0);
  const hue = hash % 360;

  return `hsl(${hue}, 70%, 45%)`;
}
// ----------------------------------------------------------
// NYC DOT Bus Signs
// ----------------------------------------------------------

/*
async function loadBusSigns() {
  try {
    const url =
      "https://data.cityofnewyork.us/resource/qt6m-xctn.json" +
      "?$select=sign_x_coord,sign_y_coord,sign_description,date_trunc_ymd(order_completed_on_date) as order_completed_on_date" +
      "&$where=(upper(sign_description)%20like%20'%25BUS%20STOP%25'%20OR%20upper(sign_description)%20like%20'%25BUS%20LANE%25'%20OR%20upper(sign_description)%20like%20'%25BUSES%20ONLY%25')%20AND%20record_type%20=%20'Current'" + 
      "&$limit=50000";

    const data = await fetchJSON(url);

    data.forEach(sign => {
      const x = safeNumber(sign.sign_x_coord);
      const y = safeNumber(sign.sign_y_coord);

      if (x === null || y === null) return;

      // Convert from EPSG:2260 to WGS84
      const [lat, lon] = epsg2260ToWGS84(x, y);

      if (!Number.isFinite(lat) || !Number.isFinite(lon)) return;

      const desc = (sign.sign_description || "").toUpperCase();

      // Color bus lane signs indigo, bus stop signs light blue
      const signColor = desc.includes("LANE")
        ? "#4B0082" // indigo
        : desc.includes("ONLY")
        ? "#4B0082" // light blue
        : desc.includes("STOP")
        ? "#66CCFF" // light blue
        : "#6c757d"; // default gray

      const tooltipText = sign.order_completed_on_date
        ? `${sign.sign_description}<br>Completed: ${sign.order_completed_on_date}`
        : sign.sign_description || "Bus Sign";

      L.circleMarker([lat, lon], {
        radius: 4,
        color: signColor,
        fillColor: signColor,
        fillOpacity: 0.8,
        weight: 1
      })
        .bindTooltip(tooltipText)
        .addTo(busSignsLayer);
    });

    console.log(`Loaded ${data.length} bus signs`);
  } catch (err) {
    console.error("Bus signs load failed:", err);
  }
}

*/

async function loadBusSigns() {
  try {
    const url =
      "https://data.cityofnewyork.us/resource/qt6m-xctn.json" +
      "?$select=sign_x_coord,sign_y_coord,sign_description,date_trunc_ymd(order_completed_on_date)%20as%20order_completed_on_date" +
      "&$where=(upper(sign_description)%20like%20'%25BUS%20STOP%25'%20OR%20upper(sign_description)%20like%20'%25BUS%20LANE%25'%20OR%20upper(sign_description)%20like%20'%25BUSES%20ONLY%25')%20AND%20record_type%20=%20'Current'" + 
      "&$limit=50000";

    const data = await fetchJSON(url);

    data.forEach(sign => {
      const x = safeNumber(sign.sign_x_coord);
      const y = safeNumber(sign.sign_y_coord);

      if (x === null || y === null) return;

      const [lat, lon] = epsg2260ToWGS84(x, y);
      if (!Number.isFinite(lat) || !Number.isFinite(lon)) return;

      const desc = (sign.sign_description || "").toUpperCase();

      // ------------------------------
      // 1. Determine icon + icon color
      // ------------------------------
      let iconChar = null;
      let iconColor = null;

      if (desc.includes("SINGLE ARROW")) {
        iconChar = "\u2192";           // →
        iconColor = "darkblue";

      } else if (desc.match(/<-+>/)) {
        iconChar = "\u2194";           // ↔
        iconColor = "darkblue";

      } else if ((desc.includes("LANE") || desc.includes("ONLY")) &&
                 desc.includes("6 O'CLOCK ARROW")) {
        iconChar = "\u21D3";           // ⇓
        iconColor = "#B22222";         // brick red

      } else if ((desc.includes("LANE") || desc.includes("ONLY")) &&
                 desc.includes("7 O'CLOCK ARROW")) {
        iconChar = "\u21D9";           // ⇙
        iconColor = "#B22222";         // brick red
      }

      // ----------------------------------------------
      // 2. Existing color logic for circle markers
      // ----------------------------------------------
      const signColor = desc.includes("LANE")
        ? "#4B0082"
        : desc.includes("ONLY")
        ? "#4B0082"
        : desc.includes("STOP")
        ? "#66CCFF"
        : "#6c757d";

      const tooltipText = sign.order_completed_on_date
        ? `${sign.sign_description}<br>Completed: ${sign.order_completed_on_date}`
        : sign.sign_description || "Bus Sign";

      // ----------------------------------------------
      // 3. If an icon was matched, use an L.divIcon
      // ----------------------------------------------
      if (iconChar) {
        const divIcon = L.divIcon({
          className: "",
          html: `<span style="font-size:18px;color:${iconColor};">${iconChar}</span>`
        });

        L.marker([lat, lon], { icon: divIcon })
          .bindTooltip(tooltipText)
          .addTo(busSignsLayer);

      } else {
        // Fallback: original circle marker
        L.circleMarker([lat, lon], {
          radius: 4,
          color: signColor,
          fillColor: signColor,
          fillOpacity: 0.8,
          weight: 1
        })
          .bindTooltip(tooltipText)
          .addTo(busSignsLayer);
      }
    });

    console.log(`Loaded ${data.length} bus signs`);
  } catch (err) {
    console.error("Bus signs load failed:", err);
  }
}


// ----------------------------------------------------------
// NYC DOT Bus Lanes
// ----------------------------------------------------------

async function loadBusLanes() {
  try {
    const url =
      "https://data.cityofnewyork.us/resource/ycrg-ses3.json?$limit=50000";

    const rows = await fetchJSON(url);

    const features = rows
      .filter(r => r.the_geom)
      .map(r => {
        let geom = r.the_geom;

        if (typeof geom === "string") {
          try {
            geom = JSON.parse(geom);
          } catch {
            return null;
          }
        }

        return {
          type: "Feature",
          geometry: geom,
          properties: r
        };
      })
      .filter(Boolean);


  L.geoJSON(
    {
      type: "FeatureCollection",
      features
    },
    {
      style: {
        color: "red",
        weight: 9,
        opacity: 0.5
      },
      onEachFeature: function (feature, layer) {
        const p = feature.properties;
  
        // Build label text
        const label =
          `${p.Days || ""} ` +
          `${p.Hours || ""} ` +
          `${p.Lane_Type || ""} ` +
          `${p.Lane_Width || ""}`.trim();
  
        // Attach a responsive tooltip
        if (label !== "") {
          layer.bindTooltip(label, {
            sticky: true,
            direction: "auto",
            opacity: 0.9,
            className: "bus-lane-tooltip"
          });
        }
      }
    }
  ).addTo(busLanesLayer);


    console.log(
      `Loaded ${features.length} bus lane features`
    );
  } catch (err) {
    console.error("Bus lanes load failed:", err);
  }
}

// ----------------------------------------------------------
// Initialization
// ----------------------------------------------------------

async function init() {
  console.log("Loading bus infrastructure layers...");

  const results = await Promise.allSettled([
    loadGTFSFeeds(),
    loadBusSigns(),
    loadBusLanes()
  ]);

  results.forEach(result => {
    if (result.status === "rejected") {
      console.error(result.reason);
    }
  });

  fitToInfrastructure();

  console.log("Map initialization complete");
}

init();
