// ----------------------------------------------------------
// NYC Bus Infrastructure Map
// Static data generated by GitHub Actions
// ----------------------------------------------------------

// ----------------------------------------------------------
// Map Initialization
// ----------------------------------------------------------

const map = L.map("map", {
  preferCanvas: true
}).setView([40.71, -74.00], 12);

L.tileLayer(
  "https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png",
  {
    attribution: "© OpenStreetMap contributors © CARTO",
    maxZoom: 19
  }
).addTo(map);

// ----------------------------------------------------------
// Layers
// ----------------------------------------------------------

const busStopsLayer = L.layerGroup();
const busRoutesLayer = L.layerGroup();
const busSignsLayer = L.layerGroup();
const busLanesLayer = L.layerGroup();

busStopsLayer.addTo(map);
busRoutesLayer.addTo(map);
busSignsLayer.addTo(map);
busLanesLayer.addTo(map);

L.control.layers(
  null,
  {
    "Bus Stops": busStopsLayer,
    "Bus Routes": busRoutesLayer,
    "Bus Signs": busSignsLayer,
    "Bus Lanes": busLanesLayer
  },
  {
    collapsed: false
  }
).addTo(map);

// ----------------------------------------------------------
// Utilities
// ----------------------------------------------------------

async function fetchJSON(url) {
  const resp = await fetch(url, {
    cache: "no-store"
  });

  if (!resp.ok) {
    throw new Error(`${url}: ${resp.status}`);
  }

  return resp.json();
}

function safeNumber(value) {
  const n = Number(value);
  return Number.isFinite(n) ? n : null;
}

function fitToInfrastructure() {
  const groups = [
    busRoutesLayer,
    busStopsLayer,
    busLanesLayer
  ];

  let bounds = null;

  groups.forEach(layer => {
    if (
      layer.getLayers &&
      layer.getLayers().length > 0 &&
      layer.getBounds
    ) {
      const b = layer.getBounds();

      if (b.isValid()) {
        bounds = bounds ? bounds.extend(b) : b;
      }
    }
  });

  if (bounds?.isValid()) {
    map.fitBounds(bounds, {
      padding: [20, 20]
    });
  }
}

// ----------------------------------------------------------
// Proj4 integration and helpers
// ----------------------------------------------------------

function ensureProj4() {
  if (typeof window !== 'undefined' && window.proj4) {
    return Promise.resolve();
  }

  return new Promise((resolve, reject) => {
    // Load proj4 from CDN
    const script = document.createElement('script');
    script.src = 'https://cdnjs.cloudflare.com/ajax/libs/proj4js/2.8.0/proj4.js';
    script.onload = () => resolve();
    script.onerror = () => reject(new Error('Failed to load proj4.js from CDN'));
    document.head.appendChild(script);
  });
}

function defineEPSG2260() {
  if (!window.proj4) return;

  // Define EPSG:2260 (NAD83 / New York Long Island (ftUS))
  // Using proj4 definition with US survey foot units
  const def = "+proj=lcc +lat_1=40.66666666666666 +lat_2=41.03333333333333 +lat_0=40.16666666666666 +lon_0=-74 +x_0=984250.0 +y_0=0 +datum=NAD83 +units=us-ft +no_defs";

  try {
    // Only define if not already present
    if (!proj4.defs['EPSG:2260']) {
      proj4.defs('EPSG:2260', def);
    }
  } catch (e) {
    // Some proj4 builds use proj4.defs as function only; still safe to call
    try {
      proj4('EPSG:2260', def);
    } catch (ignore) {}
  }
}

function projectPointEPSG2260ToWGS84(x_ft, y_ft) {
  // proj4 returns [lon, lat]
  const p = proj4('EPSG:2260', 'WGS84', [Number(x_ft), Number(y_ft)]);
  return [p[1], p[0]]; // [lat, lon]
}

function isLikelyProjectedCoord(coord) {
  // Heuristic: geographic lon/lat are within [-180,180] and [-90,90]. Projected (US-ft) will have much larger magnitudes.
  if (!Array.isArray(coord) || coord.length < 2) return false;
  const x = Math.abs(coord[0]);
  const y = Math.abs(coord[1]);
  return x > 1000 || y > 1000;
}

function reprojectGeometryToWGS84(geom) {
  if (!geom || !geom.type || !geom.coordinates) return geom;

  function reprojectCoords(coords) {
    if (typeof coords[0] === 'number' && typeof coords[1] === 'number') {
      if (!isLikelyProjectedCoord(coords)) return [coords[1], coords[0]]; // already lon/lat
      return projectPointEPSG2260ToWGS84(coords[0], coords[1]);
    }

    return coords.map(c => reprojectCoords(c));
  }

  return {
    type: geom.type,
    coordinates: reprojectCoords(geom.coordinates)
  };
}

// ----------------------------------------------------------
// Marker icons (SVG data URLs)
// ----------------------------------------------------------

function svgDataUrl(color, letter) {
  const svg = `<?xml version="1.0" encoding="UTF-8"?>\n<svg xmlns='http://www.w3.org/2000/svg' width='36' height='36' viewBox='0 0 36 36'>\n  <circle cx='18' cy='18' r='16' fill='${color}' stroke='#ffffff' stroke-width='2'/>\n  <text x='18' y='22' font-family='Arial, sans-serif' font-size='14' fill='#ffffff' text-anchor='middle' font-weight='bold'>${letter}</text>\n</svg>`;
  return 'data:image/svg+xml;utf8,' + encodeURIComponent(svg);
}

const stopIcon = L.icon({
  iconUrl: svgDataUrl('#0066ff', 'S'),
  iconSize: [24, 24],
  iconAnchor: [12, 12],
  popupAnchor: [0, -12]
});

const laneIcon = L.icon({
  iconUrl: svgDataUrl('#f77f00', 'L'),
  iconSize: [24, 24],
  iconAnchor: [12, 12],
  popupAnchor: [0, -12]
});

const defaultSignIcon = L.icon({
  iconUrl: svgDataUrl('#d62828', 'B'),
  iconSize: [24, 24],
  iconAnchor: [12, 12],
  popupAnchor: [0, -12]
});

// ----------------------------------------------------------
// Coordinate Conversion (fallback implementation preserved)
// ----------------------------------------------------------

/**
 * Fallback inverse Lambert Conformal Conic (2SP) implementation
 * on NAD83 ellipsoid. Used if proj4 is not available.
 */
function epsg2260InverseLCCFallback(x_ft, y_ft) {
  // EPSG:2260 LCC parameters
  const lat1 = 40.66666666666666 * Math.PI / 180;
  const lat2 = 41.03333333333333 * Math.PI / 180;
  const lat0 = 40.16666666666666 * Math.PI / 180;
  const lon0 = -74.0 * Math.PI / 180;

  const x0_ft = 984250.0;
  const y0_ft = 0.0;
  const usFtToMeters = 0.3048006096012192;
  const x = (x_ft - x0_ft) * usFtToMeters;
  const y = (y_ft - y0_ft) * usFtToMeters;

  const a = 6378137.0;
  const f = 1 / 298.257222101;
  const e = Math.sqrt(2 * f - f * f);

  function m(phi) {
    return Math.cos(phi) / Math.sqrt(1 - (e * e) * Math.sin(phi) * Math.sin(phi));
  }

  function t(phi) {
    const sinp = Math.sin(phi);
    const part = (1 - e * sinp) / (1 + e * sinp);
    return Math.tan(Math.PI / 4 - phi / 2) / Math.pow(part, e / 2);
  }

  const m1 = m(lat1);
  const m2 = m(lat2);
  const t1 = t(lat1);
  const t2 = t(lat2);
  const t0 = t(lat0);

  const n = Math.log(m1 / m2) / Math.log(t1 / t2);
  const F = m1 / (n * Math.pow(t1, n));
  const rho0 = a * F * Math.pow(t0, n);

  const rho = Math.sqrt(x * x + Math.pow(rho0 - y, 2));
  const theta = Math.atan2(x, rho0 - y);
  const tVal = Math.pow(rho / (a * F), 1 / n);

  let phi = Math.PI / 2 - 2 * Math.atan(tVal);

  for (let i = 0; i < 15; i++) {
    const esin = e * Math.sin(phi);
    const phiNext = Math.PI / 2 - 2 * Math.atan(tVal * Math.pow((1 - esin) / (1 + esin), e / 2));
    if (Math.abs(phiNext - phi) < 1e-12) {
      phi = phiNext;
      break;
    }
    phi = phiNext;
  }

  const lat = phi * 180 / Math.PI;
  const lon = (lon0 + theta / n) * 180 / Math.PI;

  return [lat, lon];
}

/**
 * Main wrapper to convert EPSG:2260 -> WGS84. Uses proj4 if available, otherwise falls back.
 */
function epsg2260ToWGS84(x_ft, y_ft) {
  try {
    if (typeof window !== 'undefined' && window.proj4 && proj4.defs && proj4.defs['EPSG:2260']) {
      return projectPointEPSG2260ToWGS84(x_ft, y_ft);
    }
  } catch (e) {
    // ignore and fallback
  }

  return epsg2260InverseLCCFallback(x_ft, y_ft);
}

// ----------------------------------------------------------
// Cached GTFS Data
// ----------------------------------------------------------

async function loadCachedGTFS() {
  try {
    const [stops, shapes] = await Promise.all([
      fetchJSON("data/stops.json"),
      fetchJSON("data/shapes.json")
    ]);

    drawStops(stops);
    drawShapes(shapes);

    console.log(
      `Loaded ${stops.length} stops and ${shapes.length} shapes`
    );
  } catch (err) {
    console.error("GTFS cache load failed:", err);
  }
}

// ----------------------------------------------------------
// Stops
// ----------------------------------------------------------

function drawStops(stops) {
  stops.forEach(stop => {
    const lat = safeNumber(stop.lat);
    const lon = safeNumber(stop.lon);

    if (lat === null || lon === null) return;

    L.circleMarker([lat, lon], {
      radius: 3,
      color: "#0066ff",
      fillColor: "#0066ff",
      fillOpacity: 0.7,
      weight: 1
    })
      .bindTooltip(stop.stop_name || stop.stop_id || "")
      .addTo(busStopsLayer);
  });
}

// ----------------------------------------------------------
// Route Shapes
// ----------------------------------------------------------

function drawShapes(shapes) {
  shapes.forEach(shape => {
    if (!Array.isArray(shape.points)) return;

    const pts = shape.points
      .map(p => {
        if (Array.isArray(p)) {
          return [Number(p[0]), Number(p[1])];
        }

        return [
          Number(p.lat),
          Number(p.lon)
        ];
      })
      .filter(
        p =>
          Number.isFinite(p[0]) &&
          Number.isFinite(p[1])
      );

    if (pts.length < 2) return;

    L.polyline(pts, {
      color: "#6f42c1",
      weight: 2,
      opacity: 0.6
    })
      .bindTooltip(shape.route_id || "")
      .addTo(busRoutesLayer);
  });
}

// ----------------------------------------------------------
// NYC DOT Bus Signs
// ----------------------------------------------------------

async function loadBusSigns() {
  try {
    const url =
-      "https://data.cityofnewyork.us/resource/qt6m-xctn.json" +
-      "?$select=sign_x_coord,sign_y_coord,sign_description" +
-      "&$where=upper(sign_description)%20like%20'%25BUS%25'" +
-      "&$limit=50000";
+      "https://data.cityofnewyork.us/resource/qt6m-xctn.json" +
+      "?$select=sign_x_coord,sign_y_coord,sign_description,record_type" +
+      "&$where=record_type='Current'%20AND%20upper(sign_description)%20like%20'%25BUS%25'" +
+      "&$limit=50000";

    const data = await fetchJSON(url);

    // Ensure proj4 is loaded and EPSG:2260 is defined
    try {
      await ensureProj4();
      defineEPSG2260();
    } catch (e) {
      console.warn('proj4 not available; falling back to internal reprojection');
    }

    data.forEach(sign => {
      const x = safeNumber(sign.sign_x_coord);
      const y = safeNumber(sign.sign_y_coord);

      if (x === null || y === null) return;

      // Convert from EPSG:2260 to WGS84
      const [lat, lon] = epsg2260ToWGS84(x, y);

      if (!Number.isFinite(lat) || !Number.isFinite(lon)) return;

      const desc = (sign.sign_description || '').toUpperCase();
      let icon = defaultSignIcon;

      if (desc.includes('STOP') || desc.includes('BUS STOP') || desc.includes('BUSSTOP')) {
        icon = stopIcon;
      } else if (desc.includes('LANE') || desc.includes('BUS LANE') || desc.includes('BUSLANE')) {
        icon = laneIcon;
      }

      L.marker([lat, lon], { icon })
        .bindTooltip(sign.sign_description || "Bus Sign")
        .addTo(busSignsLayer);
    });

    console.log(`Loaded ${data.length} bus signs`);
  } catch (err) {
    console.error("Bus signs load failed:", err);
  }
}

// ----------------------------------------------------------
// NYC DOT Bus Lanes
// ----------------------------------------------------------

async function loadBusLanes() {
  try {
    const url =
      "https://data.cityofnewyork.us/resource/ycrg-ses3.json?$limit=50000";

    const rows = await fetchJSON(url);

    const features = rows
      .filter(r => r.the_geom)
      .map(r => {
        let geom = r.the_geom;

        if (typeof geom === "string") {
          try {
            geom = JSON.parse(geom);
          } catch {
            return null;
          }
        }

        return {
          type: "Feature",
          geometry: geom,
          properties: r
        };
      })
      .filter(Boolean);

    // Attempt to load proj4 and reproject geometries if they appear to be in EPSG:2260
    try {
      await ensureProj4();
      defineEPSG2260();

      const reprojected = features.map(f => {
        try {
          const geom = f.geometry;
          // Only reproject if coordinates look projected
          let shouldReproject = false;

          function scanCoords(coords) {
            if (typeof coords[0] === 'number' && typeof coords[1] === 'number') {
              if (isLikelyProjectedCoord(coords)) shouldReproject = true;
              return;
            }
            for (const c of coords) scanCoords(c);
          }

          if (geom && geom.coordinates) scanCoords(geom.coordinates);

          if (shouldReproject) {
            return {
              ...f,
              geometry: reprojectGeometryToWGS84(geom)
            };
          }

          return f;
        } catch (e) {
          return f;
        }
      });

      L.geoJSON(
        {
          type: "FeatureCollection",
          features: reprojected
        },
        {
          style: {
            color: "#f77f00",
            weight: 3,
            opacity: 0.8
          }
        }
      ).addTo(busLanesLayer);
    } catch (e) {
      // proj4 unavailable; add original geometries (assumed to be GeoJSON WGS84 already)
      L.geoJSON(
        {
          type: "FeatureCollection",
          features
        },
        {
          style: {
            color: "#f77f00",
            weight: 3,
            opacity: 0.8
          }
        }
      ).addTo(busLanesLayer);
    }

    console.log(
      `Loaded ${features.length} bus lane features`
    );
  } catch (err) {
    console.error("Bus lanes load failed:", err);
  }
}

// ----------------------------------------------------------
// Initialization
// ----------------------------------------------------------

async function init() {
  console.log("Loading bus infrastructure layers...");

  const results = await Promise.allSettled([
    loadCachedGTFS(),
    loadBusSigns(),
    loadBusLanes()
  ]);

  results.forEach(result => {
    if (result.status === "rejected") {
      console.error(result.reason);
    }
  });

  fitToInfrastructure();

  console.log("Map initialization complete");
}

init();
