// ----------------------------------------------------------
// NYC Bus Infrastructure Map
// Static data generated by GitHub Actions
// ----------------------------------------------------------

// ----------------------------------------------------------
// Map Initialization
// ----------------------------------------------------------

const map = L.map("map", {
  preferCanvas: true
}).setView([40.71, -74.00], 12);

L.tileLayer(
  "https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png",
  {
    attribution: "© OpenStreetMap contributors © CARTO",
    maxZoom: 19
  }
).addTo(map);

// ----------------------------------------------------------
// Layers
// ----------------------------------------------------------

const busStopsLayer = L.layerGroup();
const busRoutesLayer = L.layerGroup();
const busSignsLayer = L.layerGroup();
const busLanesLayer = L.layerGroup();

busStopsLayer.addTo(map);
busRoutesLayer.addTo(map);
busSignsLayer.addTo(map);
busLanesLayer.addTo(map);

L.control.layers(
  null,
  {
    "Bus Stops": busStopsLayer,
    "Bus Routes": busRoutesLayer,
    "Bus Signs": busSignsLayer,
    "Bus Lanes": busLanesLayer
  },
  {
    collapsed: false
  }
).addTo(map);

// ----------------------------------------------------------
// Utilities
// ----------------------------------------------------------

async function fetchJSON(url) {
  const resp = await fetch(url, {
    cache: "no-store"
  });

  if (!resp.ok) {
    throw new Error(`${url}: ${resp.status}`);
  }

  return resp.json();
}

function safeNumber(value) {
  const n = Number(value);
  return Number.isFinite(n) ? n : null;
}

function fitToInfrastructure() {
  const groups = [
    busRoutesLayer,
    busStopsLayer,
    busLanesLayer
  ];

  let bounds = null;

  groups.forEach(layer => {
    if (
      layer.getLayers &&
      layer.getLayers().length > 0 &&
      layer.getBounds
    ) {
      const b = layer.getBounds();

      if (b.isValid()) {
        bounds = bounds ? bounds.extend(b) : b;
      }
    }
  });

  if (bounds?.isValid()) {
    map.fitBounds(bounds, {
      padding: [20, 20]
    });
  }
}

// ----------------------------------------------------------
// Cached GTFS Data
// ----------------------------------------------------------

async function loadCachedGTFS() {
  try {
    const [stops, shapes] = await Promise.all([
      fetchJSON("data/stops.json"),
      fetchJSON("data/shapes.json")
    ]);

    drawStops(stops);
    drawShapes(shapes);

    console.log(
      `Loaded ${stops.length} stops and ${shapes.length} shapes`
    );
  } catch (err) {
    console.error("GTFS cache load failed:", err);
  }
}

// ----------------------------------------------------------
// Stops
// ----------------------------------------------------------

function drawStops(stops) {
  stops.forEach(stop => {
    const lat = safeNumber(stop.lat);
    const lon = safeNumber(stop.lon);

    if (lat === null || lon === null) return;

    L.circleMarker([lat, lon], {
      radius: 3,
      color: "#0066ff",
      fillColor: "#0066ff",
      fillOpacity: 0.7,
      weight: 1
    })
      .bindTooltip(stop.stop_name || stop.stop_id || "")
      .addTo(busStopsLayer);
  });
}

// ----------------------------------------------------------
// Route Shapes
// ----------------------------------------------------------

function drawShapes(shapes) {
  shapes.forEach(shape => {
    if (!Array.isArray(shape.points)) return;

    const pts = shape.points
      .map(p => {
        if (Array.isArray(p)) {
          return [Number(p[0]), Number(p[1])];
        }

        return [
          Number(p.lat),
          Number(p.lon)
        ];
      })
      .filter(
        p =>
          Number.isFinite(p[0]) &&
          Number.isFinite(p[1])
      );

    if (pts.length < 2) return;

    L.polyline(pts, {
      color: "#6f42c1",
      weight: 2,
      opacity: 0.6
    })
      .bindTooltip(shape.route_id || "")
      .addTo(busRoutesLayer);
  });
}

// ----------------------------------------------------------
// NYC DOT Bus Signs
// ----------------------------------------------------------

async function loadBusSigns() {
  try {
    const url =
      "https://data.cityofnewyork.us/resource/qiz3-aqxq.json" +
      "?$select=latitude,longitude,sign_description" +
      "&$where=upper(sign_description)%20like%20'%25BUS%25'" +
      "&$limit=50000";

    const data = await fetchJSON(url);

    data.forEach(sign => {
      const lat = safeNumber(sign.latitude);
      const lon = safeNumber(sign.longitude);

      if (lat === null || lon === null) return;

      L.circleMarker([lat, lon], {
        radius: 4,
        color: "#d62828",
        fillColor: "#d62828",
        fillOpacity: 0.8,
        weight: 1
      })
        .bindTooltip(
          sign.sign_description || "Bus Sign"
        )
        .addTo(busSignsLayer);
    });

    console.log(`Loaded ${data.length} bus signs`);
  } catch (err) {
    console.error("Bus signs load failed:", err);
  }
}

// ----------------------------------------------------------
// NYC DOT Bus Lanes
// ----------------------------------------------------------

async function loadBusLanes() {
  try {
    const url =
      "https://data.cityofnewyork.us/resource/ycrg-ses3.json?$limit=50000";

    const rows = await fetchJSON(url);

    const features = rows
      .filter(r => r.the_geom)
      .map(r => {
        let geom = r.the_geom;

        if (typeof geom === "string") {
          try {
            geom = JSON.parse(geom);
          } catch {
            return null;
          }
        }

        return {
          type: "Feature",
          geometry: geom,
          properties: r
        };
      })
      .filter(Boolean);

    L.geoJSON(
      {
        type: "FeatureCollection",
        features
      },
      {
        style: {
          color: "#f77f00",
          weight: 3,
          opacity: 0.8
        }
      }
    ).addTo(busLanesLayer);

    console.log(
      `Loaded ${features.length} bus lane features`
    );
  } catch (err) {
    console.error("Bus lanes load failed:", err);
  }
}

// ----------------------------------------------------------
// Initialization
// ----------------------------------------------------------

async function init() {
  console.log("Loading bus infrastructure layers...");

  const results = await Promise.allSettled([
    loadCachedGTFS(),
    loadBusSigns(),
    loadBusLanes()
  ]);

  results.forEach(result => {
    if (result.status === "rejected") {
      console.error(result.reason);
    }
  });

  fitToInfrastructure();

  console.log("Map initialization complete");
}

init();
